"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)

# Load environment from repository root .env before reading env vars
# Repo root is two levels above BASE_DIR (which is .../src/mysite)
_env_path = os.path.abspath(os.path.join(BASE_DIR, "..", "..", ".env"))
if os.path.exists(_env_path):
    try:
        from dotenv import load_dotenv  # type: ignore
        # override=True ensures refreshed values from .env take precedence
        load_dotenv(_env_path, override=True)
    except Exception:
        pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "catalog",
    "home",
    "search",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "mozilla_django_oidc",  # Required for OIDC authentication
    "auditlog",  # Field-level change tracking
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "auditlog.middleware.AuditlogMiddleware",  # Track user for audit logs
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

# Optional: override DATABASES from env DATABASE_URL if provided
db_url = os.environ.get("DATABASE_URL")
if db_url:
    parsed = urlparse(db_url)
    if parsed.scheme.startswith("postgres"):
        DATABASES["default"] = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": parsed.path.lstrip("/"),
            "USER": parsed.username,
            "PASSWORD": parsed.password,
            "HOST": parsed.hostname,
            "PORT": parsed.port,
        }
    else:
        raise ImproperlyConfigured("Unsupported DATABASE_URL scheme: %s" % parsed.scheme)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

WAGTAIL_SITE_NAME = "mysite"

# Enable user management in Wagtail Admin
WAGTAIL_USER_EDIT_FORM = 'wagtail.users.forms.UserEditForm'
WAGTAIL_USER_CREATION_FORM = 'wagtail.users.forms.UserCreationForm'
WAGTAIL_USER_CUSTOM_FIELDS = []  # Can add custom fields later if needed

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

# Authentication backends placeholder for OIDC (to be completed in devops step)
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
)

# OIDC base configuration (values expected in environment)
OIDC_RP_CLIENT_ID = os.environ.get("PUBLIC_KEYCLOAK_CLIENT_ID", "")
OIDC_RP_CLIENT_SECRET = os.environ.get("KEYCLOAK_CLIENT_SECRET", "")
OIDC_OP_BASE_URL = os.environ.get("PUBLIC_KEYCLOAK_URL", "http://localhost:8080")
OIDC_REALM = os.environ.get("PUBLIC_KEYCLOAK_REALM", "")

# Derived endpoints (Keycloak OpenID Connect endpoints)
if OIDC_OP_BASE_URL and OIDC_REALM:
    OIDC_OP_AUTHORIZATION_ENDPOINT = f"{OIDC_OP_BASE_URL}/realms/{OIDC_REALM}/protocol/openid-connect/auth"
    OIDC_OP_TOKEN_ENDPOINT = f"{OIDC_OP_BASE_URL}/realms/{OIDC_REALM}/protocol/openid-connect/token"
    OIDC_OP_USER_ENDPOINT = f"{OIDC_OP_BASE_URL}/realms/{OIDC_REALM}/protocol/openid-connect/userinfo"
    OIDC_OP_JWKS_ENDPOINT = f"{OIDC_OP_BASE_URL}/realms/{OIDC_REALM}/protocol/openid-connect/certs"

# Defaults suitable for local dev; adjust in production
OIDC_VERIFY_SSL = False
OIDC_RP_SIGN_ALGO = os.environ.get("OIDC_RP_SIGN_ALGO", "RS256")
OIDC_RP_SCOPES = "openid email profile"
OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = 3600  # 1 hour
OIDC_USE_NONCE = True
OIDC_STORE_ID_TOKEN = True
OIDC_STORE_ACCESS_TOKEN = True

# Explicit redirect URI for OIDC callback (must match Keycloak client configuration)
OIDC_CALLBACK_PATH = "/oidc/callback/"  # Default callback path

# Authentication redirect URLs
OIDC_AUTHENTICATION_CALLBACK_URL = "oidc_authentication_callback"

