# Generated by Django 5.2.7 on 2026-06-15 15:32

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_aboutpage_body_alter_guidancepage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_heading',
            field=models.CharField(blank=True, default='About this project', max_length=120),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_tags',
            field=wagtail.fields.StreamField([('tag', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Tag'})}),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='badge_text',
            field=models.CharField(blank=True, default='About the project', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_cards',
            field=wagtail.fields.StreamField([('card', 6)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-envelope', 'Envelope'), ('fa-plus', 'Plus'), ('fa-comment', 'Comment'), ('fa-handshake', 'Handshake')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Green (filled) button. Leave unchecked for an outline button.', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2), ('button_label', 3), ('button_url', 4), ('primary', 5)]], {})}),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='contact_heading',
            field=models.CharField(blank=True, default='Get in touch', max_length=120),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_highlight',
            field=models.CharField(blank=True, default='standardize', help_text='A word within the title shown in green (optional).', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(default='Built to standardize how adaptation gets measured', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='key_features',
            field=wagtail.fields.StreamField([('feature', 4)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-people-group', 'People (Community)'), ('fa-globe', 'Globe'), ('fa-chart-line', 'Chart'), ('fa-leaf', 'Leaf'), ('fa-bullseye', 'Target'), ('fa-shield', 'Shield'), ('fa-circle-check', 'Check')]}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('purple', 'Purple'), ('blue', 'Blue'), ('emerald', 'Green'), ('orange', 'Orange'), ('rose', 'Rose')]}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('icon', 0), ('color', 1), ('title', 2), ('description', 3)]], {})}),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='partners',
            field=wagtail.fields.StreamField([('partner', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 150}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Small green label, e.g. 'Research & data'", 'max_length': 80, 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload a logo (preferred)', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Or a static path, e.g. images/ilri_logo.jpg', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'Official website (opens in a new tab)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('name', 0), ('tag', 1), ('description', 2), ('logo', 3), ('logo_url', 4), ('url', 5)]], {})}),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team',
            field=wagtail.fields.StreamField([('member', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 3}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('blue', 'Blue'), ('emerald', 'Green'), ('amber', 'Amber'), ('purple', 'Purple'), ('rose', 'Rose')]}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('initials', 0), ('color', 1), ('name', 2), ('role', 3), ('description', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='guidancepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('feature_card', 7), ('partner', 14), ('team_member', 19), ('section', 25), ('html', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Section title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Rich formatted text', 'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-globe', 'Globe (Global)'), ('fa-check-circle', 'Check (Validated)'), ('fa-users', 'Users (Community)'), ('fa-bullseye', 'Target (Goal)'), ('fa-chart-line', 'Chart (Data)'), ('fa-leaf', 'Leaf (Environment)'), ('fa-shield', 'Shield (Protection)')], 'help_text': 'Select the icon for the card'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red')]}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Feature title', 'max_length': 100}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description'}), 7: ('wagtail.blocks.StructBlock', [[('icon', 3), ('icon_color', 4), ('title', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Organization name', 'max_length': 100}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Acronym (e.g. IWMI, ILRI)', 'max_length': 20}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Role (e.g. Data Standards & Coordination)', 'max_length': 100}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'Collaboration description'}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Logo path (e.g. images/iwmi_logo.jpg)', 'max_length': 255, 'required': False}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange')]}), 14: ('wagtail.blocks.StructBlock', [[('name', 8), ('acronym', 9), ('role', 10), ('description', 11), ('logo_url', 12), ('acronym_color', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Full name', 'max_length': 100}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Role/Position', 'max_length': 100}), 17: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short biography or specialty'}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Initials for avatar (e.g. JD)', 'max_length': 3}), 19: ('wagtail.blocks.StructBlock', [[('name', 15), ('role', 16), ('description', 17), ('initials', 18), ('avatar_color', 4)]], {}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-bullseye', 'Target'), ('fa-info-circle', 'Info'), ('fa-envelope', 'Email'), ('fa-users', 'Users')]}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple')]}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 23: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Section content'}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('blue', 'Light blue'), ('gray', 'Light gray')]}), 25: ('wagtail.blocks.StructBlock', [[('icon', 20), ('icon_color', 21), ('title', 22), ('content', 23), ('background_color', 24)]], {}), 26: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '⚠️ Advanced: Custom HTML', 'icon': 'code'})}),
        ),
        migrations.AlterField(
            model_name='trackingframeworkpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('feature_card', 7), ('partner', 14), ('team_member', 19), ('section', 25), ('html', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Section title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Rich formatted text', 'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-globe', 'Globe (Global)'), ('fa-check-circle', 'Check (Validated)'), ('fa-users', 'Users (Community)'), ('fa-bullseye', 'Target (Goal)'), ('fa-chart-line', 'Chart (Data)'), ('fa-leaf', 'Leaf (Environment)'), ('fa-shield', 'Shield (Protection)')], 'help_text': 'Select the icon for the card'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red')]}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Feature title', 'max_length': 100}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description'}), 7: ('wagtail.blocks.StructBlock', [[('icon', 3), ('icon_color', 4), ('title', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Organization name', 'max_length': 100}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Acronym (e.g. IWMI, ILRI)', 'max_length': 20}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Role (e.g. Data Standards & Coordination)', 'max_length': 100}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'Collaboration description'}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Logo path (e.g. images/iwmi_logo.jpg)', 'max_length': 255, 'required': False}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange')]}), 14: ('wagtail.blocks.StructBlock', [[('name', 8), ('acronym', 9), ('role', 10), ('description', 11), ('logo_url', 12), ('acronym_color', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Full name', 'max_length': 100}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Role/Position', 'max_length': 100}), 17: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short biography or specialty'}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Initials for avatar (e.g. JD)', 'max_length': 3}), 19: ('wagtail.blocks.StructBlock', [[('name', 15), ('role', 16), ('description', 17), ('initials', 18), ('avatar_color', 4)]], {}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-bullseye', 'Target'), ('fa-info-circle', 'Info'), ('fa-envelope', 'Email'), ('fa-users', 'Users')]}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple')]}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 23: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Section content'}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('blue', 'Light blue'), ('gray', 'Light gray')]}), 25: ('wagtail.blocks.StructBlock', [[('icon', 20), ('icon_color', 21), ('title', 22), ('content', 23), ('background_color', 24)]], {}), 26: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '⚠️ Advanced: Custom HTML', 'icon': 'code'})}),
        ),
        migrations.AlterField(
            model_name='wikiinstructionspage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('feature_card', 7), ('partner', 14), ('team_member', 19), ('section', 25), ('html', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Section title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Rich formatted text', 'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-globe', 'Globe (Global)'), ('fa-check-circle', 'Check (Validated)'), ('fa-users', 'Users (Community)'), ('fa-bullseye', 'Target (Goal)'), ('fa-chart-line', 'Chart (Data)'), ('fa-leaf', 'Leaf (Environment)'), ('fa-shield', 'Shield (Protection)')], 'help_text': 'Select the icon for the card'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red')]}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Feature title', 'max_length': 100}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description'}), 7: ('wagtail.blocks.StructBlock', [[('icon', 3), ('icon_color', 4), ('title', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Organization name', 'max_length': 100}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Acronym (e.g. IWMI, ILRI)', 'max_length': 20}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Role (e.g. Data Standards & Coordination)', 'max_length': 100}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'Collaboration description'}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Logo path (e.g. images/iwmi_logo.jpg)', 'max_length': 255, 'required': False}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange')]}), 14: ('wagtail.blocks.StructBlock', [[('name', 8), ('acronym', 9), ('role', 10), ('description', 11), ('logo_url', 12), ('acronym_color', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Full name', 'max_length': 100}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Role/Position', 'max_length': 100}), 17: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short biography or specialty'}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Initials for avatar (e.g. JD)', 'max_length': 3}), 19: ('wagtail.blocks.StructBlock', [[('name', 15), ('role', 16), ('description', 17), ('initials', 18), ('avatar_color', 4)]], {}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('fa-bullseye', 'Target'), ('fa-info-circle', 'Info'), ('fa-envelope', 'Email'), ('fa-users', 'Users')]}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple')]}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 23: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Section content'}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('blue', 'Light blue'), ('gray', 'Light gray')]}), 25: ('wagtail.blocks.StructBlock', [[('icon', 20), ('icon_color', 21), ('title', 22), ('content', 23), ('background_color', 24)]], {}), 26: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '⚠️ Advanced: Custom HTML', 'icon': 'code'})}),
        ),
    ]
