# Generated by Django 5.2.16 on 2026-09-04 15:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_guidancepage_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle shown below the title', max_length=255)),
                ('body', wagtail.fields.StreamField([('definition', 2), ('paragraph', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('term', 0), ('definition', 1)]], {'icon': 'openquote'}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'})})),
            ],
            options={
                'verbose_name': 'Definitions Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
