# Generated by Django 5.2.7 on 2025-10-31 16:45

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-changed_at',),
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='wagtailcore.page')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SOPPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField()),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('ontology_uri', models.URLField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('owner_user_id', models.IntegerField(blank=True, null=True)),
                ('entry_author', models.CharField(blank=True, max_length=255)),
                ('definition', wagtail.fields.RichTextField(blank=True)),
                ('data_sources', wagtail.fields.RichTextField(blank=True)),
                ('units', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('geographic_scale', models.CharField(blank=True, max_length=150)),
                ('technical_capacity', wagtail.fields.RichTextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='catalog.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'SOP',
                'verbose_name_plural': 'SOPs',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MetricPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField()),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('ontology_uri', models.URLField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('owner_user_id', models.IntegerField(blank=True, null=True)),
                ('entry_author', models.CharField(blank=True, max_length=255)),
                ('purpose', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='catalog.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MethodPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField()),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('ontology_uri', models.URLField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('owner_user_id', models.IntegerField(blank=True, null=True)),
                ('entry_author', models.CharField(blank=True, max_length=255)),
                ('resolution', models.CharField(blank=True, max_length=150)),
                ('advantages', wagtail.fields.RichTextField(blank=True)),
                ('limitations', wagtail.fields.RichTextField(blank=True)),
                ('use_case', wagtail.fields.RichTextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='catalog.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Method',
                'verbose_name_plural': 'Methods',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='IndicatorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField()),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('ontology_uri', models.URLField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('owner_user_id', models.IntegerField(blank=True, null=True)),
                ('entry_author', models.CharField(blank=True, max_length=255)),
                ('dimension', models.CharField(blank=True, max_length=150)),
                ('indicator_type', models.CharField(blank=True, max_length=150)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='catalog.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'High Level Indicator',
                'verbose_name_plural': 'High Level Indicators',
            },
            bases=('wagtailcore.page',),
        ),
    ]
