# Generated by Django 5.2.7 on 2025-10-31 16:47

from django.db import migrations


def create_groups_and_workflow(apps, schema_editor):
    """Create RBAC groups and default Review workflow."""
    Group = apps.get_model("auth", "Group")
    Workflow = apps.get_model("wagtailcore", "Workflow")
    WorkflowTask = apps.get_model("wagtailcore", "WorkflowTask")
    GroupApprovalTask = apps.get_model("wagtailcore", "GroupApprovalTask")
    ContentType = apps.get_model("contenttypes", "ContentType")
    
    # Create groups if they don't exist
    admin_group, _ = Group.objects.get_or_create(name="Administrator")
    reviewer_group, _ = Group.objects.get_or_create(name="Reviewer")
    content_dev_group, _ = Group.objects.get_or_create(name="ContentDeveloper")
    
    # Create default workflow: Review then publish
    workflow, created = Workflow.objects.get_or_create(
        name="Review then publish",
        defaults={"active": True}
    )
    
    if created:
        # Create GroupApprovalTask with proper content_type
        task_ct = ContentType.objects.get_for_model(GroupApprovalTask)
        task = GroupApprovalTask.objects.create(
            name="Review",
            active=True,
            content_type=task_ct,
        )
        task.groups.add(reviewer_group)
        
        # Link task to workflow
        WorkflowTask.objects.create(
            workflow=workflow,
            task=task,
            sort_order=0,
        )


def remove_groups_and_workflow(apps, schema_editor):
    """Reverse migration: remove groups and workflow."""
    Group = apps.get_model("auth", "Group")
    Workflow = apps.get_model("wagtailcore", "Workflow")
    
    Group.objects.filter(name__in=["Administrator", "Reviewer", "ContentDeveloper"]).delete()
    Workflow.objects.filter(name="Review then publish").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_workflow, remove_groups_and_workflow),
    ]
