# Generated by Django 5.2.7 on 2025-10-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_indicatorpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorpage',
            options={'verbose_name': 'Indicator', 'verbose_name_plural': 'Indicators'},
        ),
    ]
