# Generated by Django 5.2.7 on 2025-11-04 20:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_delete_taggeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='soppage',
            name='activities_and_steps',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='soppage',
            name='available_tools_and_code',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='soppage',
            name='flagship_method_status',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='soppage',
            name='options_enhancing_robustness',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='soppage',
            name='options_reducing_costs',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='soppage',
            name='references',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='soppage',
            name='visual_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
