# Generated by Django 5.2.7 on 2026-06-04 16:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_soppage_activities_and_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricpage',
            name='adaptation_tracking_function',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short description of how this metric supports adaptation tracking.'),
        ),
        migrations.AddField(
            model_name='metricpage',
            name='tracks_intervention_impacts',
            field=models.BooleanField(default=False, verbose_name='Assessing intervention impacts'),
        ),
        migrations.AddField(
            model_name='metricpage',
            name='tracks_vulnerability',
            field=models.BooleanField(default=False, verbose_name='Tracking vulnerability'),
        ),
    ]
