# Generated by Django 5.2.7 on 2026-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_metricpage_adaptation_tracking_function_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soppage',
            name='estimated_time',
            field=models.CharField(blank=True, help_text="Estimated effort/time, e.g. '~2 hours', '1–2 days'.", max_length=100),
        ),
        migrations.AddField(
            model_name='soppage',
            name='method_type',
            field=models.CharField(blank=True, help_text="Primary method type, e.g. '🛰️ Satellite', 'Model', 'Field + Lab'.", max_length=100),
        ),
    ]
