# Generated by Django 5.2.7 on 2026-06-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_drop_orphan_methodpage_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodpage',
            name='cost_level',
            field=models.CharField(blank=True, help_text="Cost / accuracy note, e.g. 'Low cost', 'High accuracy'.", max_length=100),
        ),
        migrations.AddField(
            model_name='methodpage',
            name='method_type',
            field=models.CharField(blank=True, help_text="Primary approach, e.g. 'Satellite', 'Model', 'Field + Lab'.", max_length=100),
        ),
        migrations.AddField(
            model_name='methodpage',
            name='scale',
            field=models.CharField(blank=True, help_text="Scale / output note, e.g. 'Spatial', 'Plot level', 'Scenario'.", max_length=100),
        ),
    ]
