# Generated by Django 5.2.7 on 2026-06-15 04:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_methodpage_cost_level_methodpage_method_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodpage',
            name='cost_level',
        ),
        migrations.RemoveField(
            model_name='methodpage',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='methodpage',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='soppage',
            name='method_type',
        ),
        migrations.AddField(
            model_name='methodpage',
            name='resources',
            field=wagtail.fields.RichTextField(blank=True, help_text='Reference resources for this method. Use the link button to add clickable hyperlinks.'),
        ),
    ]
