# Generated by Django 5.2.16 on 2026-07-28 19:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_methodpage_cost_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soppage',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords to improve search results for this SOP.', max_length=500),
        ),
        migrations.AlterField(
            model_name='soppage',
            name='units',
            field=wagtail.fields.RichTextField(blank=True, help_text='Supports bullet lists when several units apply.'),
        ),
    ]
