# Generated by Django 5.2.16 on 2026-08-04 15:25

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_soppage_keywords_alter_soppage_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorpage',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stable ID from the bulk-import source (e.g. IND001). Used to match on re-import.', max_length=100),
        ),
        migrations.AddField(
            model_name='soppage',
            name='example_applications',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='soppage',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stable ID from the bulk-import source (e.g. SOP001). Used to match on re-import.', max_length=100),
        ),
        migrations.AddField(
            model_name='soppage',
            name='unfccc_alignment',
            field=wagtail.fields.RichTextField(blank=True, help_text='Alignment with the UNFCCC Belém Adaptation Indicators.'),
        ),
    ]
