# Generated by Django 5.2.16 on 2026-08-28 14:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_indicatorpage_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodpage',
            name='resolution',
            field=wagtail.fields.RichTextField(blank=True, help_text='Paragraph field: supports multiple lines and lists.'),
        ),
        migrations.AlterField(
            model_name='soppage',
            name='frequency',
            field=wagtail.fields.RichTextField(blank=True, help_text='Paragraph field: supports multiple lines and lists.'),
        ),
        migrations.AlterField(
            model_name='soppage',
            name='geographic_scale',
            field=wagtail.fields.RichTextField(blank=True, help_text='Paragraph field: supports multiple lines and lists.'),
        ),
    ]
